spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:file:./data/email_app_db;CIPHER=AES
    driver-class-name: org.h2.Driver
    username: sa
    password: filepassword Admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  
server:
  port: 8080

logging:
    level:
      '[org.hibernate.SQL]': DEBUG
      '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE  